import { Link } from 'react-router-dom';
import { Phone, Star, Image, ArrowRight } from 'lucide-react';
import { company } from '../data/company';
import Reveal from '../components/Reveal';
import heroImg from '../assets/641438180_937093688882819_3537828339113545737_n.jpg';
import featureImg from '../assets/639823873_937093665549488_1402015918024037118_n.jpg';
import projectImg from '../assets/641198431_937093755549479_5618946941157760348_n.jpg';

export default function Home(){return <>
 <section className="hero"><div className="container hero-grid"><Reveal direction="right"><div><p className="eyebrow">Bathroom remodeler · Newcastle upon Tyne</p><h1>Bathrooms designed for everyday comfort.</h1><p className="lead">Bathroom installation, tiling and complete room transformations from an experienced local specialist.</p><div className="actions"><a className="btn" href={company.phoneHref}><Phone size={18}/>Call {company.phone}</a><Link className="btn ghost" to="/projects">View projects</Link><a className="btn ghost" href={company.facebook} target="_blank" rel="noreferrer"><span className="facebook-mark small-mark">f</span>Facebook</a></div><div className="trust"><span><Star/> {company.rating} Google rating</span><span>{company.reviews} reviews</span><span><Image/> {company.photos} photos</span></div></div></Reveal><Reveal delay={140} direction="left"><img src={heroImg} alt="Newcastle Bathroom Company Installation" className="hero-image" loading="eager" /></Reveal></div></section>
 
 <section className="section"><div className="container split"><Reveal direction="right"><div><p className="eyebrow">What we can help with</p><h2>From tired bathrooms to calm, practical spaces</h2><p>Whether it's a small ensuite refresh or a complete multi-week renovation, we handle the full process from strip-out to the final tile.</p><div className="cards" style={{marginTop: '30px'}}>{[['Full bathroom renovations','A complete refresh of layout, finishes and fittings.'],['Shower rooms & wet rooms','Practical, accessible and carefully finished spaces.'],['Tiling & finishing','Wall and floor tiling that brings the room together.']].map(([t,d],i)=><article key={t} className="card" style={{padding: '20px', marginBottom: '15px'}}><h3>{t}</h3><p>{d}</p><Link to="/services">Learn more <ArrowRight size={16}/></Link></article>)}</div></div></Reveal><Reveal delay={120} direction="left"><img src={projectImg} alt="Wood Effect Bathroom Feature" className="split-image" loading="lazy" /></Reveal></div></section>

 <section className="section dark"><div className="container split dark"><Reveal direction="right"><img src={featureImg} alt="Quality Bathroom Finish" className="split-image" loading="lazy" /></Reveal><Reveal delay={100} direction="left"><div><p className="eyebrow">Why choose us</p><h2>Strong reviews. Real project proof.</h2><p>A perfect Google rating, extensive project photography and years of bathroom installation experience give customers confidence before the first conversation.</p><div className="actions"><Link className="btn btn-highlight" to="/reviews">See reputation highlights</Link><a className="btn ghost light-border" href={company.facebook} target="_blank" rel="noreferrer">View Facebook projects</a></div></div></Reveal></div></section>
</>}
